//! Inventory markdown emission and BEGIN/END region replacement.
//!
//! Renders four inventory tables — one per snippet kind — from the
//! per-file [`SnippetHeader`]s and substitutes each into a marked
//! region of `packaging/snippets/README.md`. The four regions are
//! delimited by:
//!
//!   <!-- BEGIN: inventory:parsers -->   ... <!-- END: inventory:parsers -->
//!   <!-- BEGIN: inventory:composers --> ... <!-- END: inventory:composers -->
//!   <!-- BEGIN: inventory:filters -->   ... <!-- END: inventory:filters -->
//!   <!-- BEGIN: inventory:functions --> ... <!-- END: inventory:functions -->
//!
//! Governing principle: header values that are AUTHORED (Summary /
//! Writes / Signature) are copied verbatim into the table cells.
//! Derived values (function Used-by, composer Writes first token)
//! are computed here from the shipped snippet bodies rather than
//! read from the header — they belong to xtask, not to the author.
//!
//! ## Category source of truth
//!
//! Each parser declares its category in its own header
//! (`// Category: ...`). [`CATEGORIES`] below is the ordered,
//! authoritative list of allowed category names — the parsers
//! renderer groups rows in this order, and [`crate::header::lint`]
//! rejects any parser header whose `Category:` value is not in this
//! list. Composers/filters/functions have no Category axis (see
//! `limpid-snippet-header-schema-unification` vault card).

use std::path::Path;

use crate::header::{SnippetHeader, SnippetKind, parse_signature};

/// Ordered, authoritative list of allowed parser categories.
///
/// The render order in the parsers inventory table follows this
/// slice exactly. To add a category: append (or insert) an entry
/// here and document it in `packaging/snippets/README.md`.
pub const CATEGORIES: &[&str] = &[
    "Transport",
    "Network firewall / IPS",
    "OSS NDR",
    "Host firewall (kernel)",
    "Cloud audit (API control plane)",
    "Cloud network (data plane)",
    "Cloud security findings",
    "Identity / IdP",
    "EDR",
    "Container / orchestration",
    "Web / proxy access",
    "Mail (MTA)",
    "DNS server",
    "Endpoint / host audit (Unix)",
    "Endpoint / host audit (Windows)",
    "Network device (switch / router)",
    "Vendor-neutral",
];

// ---------------------------------------------------------------------------
// Marker names.
// ---------------------------------------------------------------------------

const PARSERS_MARKER: &str = "inventory:parsers";
const COMPOSERS_MARKER: &str = "inventory:composers";
const FILTERS_MARKER: &str = "inventory:filters";
const FUNCTIONS_MARKER: &str = "inventory:functions";

pub fn marker_for(kind: SnippetKind) -> &'static str {
    match kind {
        SnippetKind::Parser => PARSERS_MARKER,
        SnippetKind::Composer => COMPOSERS_MARKER,
        SnippetKind::Filter => FILTERS_MARKER,
        SnippetKind::Function => FUNCTIONS_MARKER,
    }
}

// ---------------------------------------------------------------------------
// Renderers — one per kind.
// ---------------------------------------------------------------------------

/// Prefix printed at the top of every generated block, so hand
/// editors immediately see they are looking at machine output.
fn generated_notice() -> String {
    let mut s = String::new();
    s.push_str("<!-- Generated by `cargo xtask gen-snippet-inventory`. Do not\n");
    s.push_str("     edit by hand — edit the snippet headers and re-run the\n");
    s.push_str("     generator. See `Authoring conventions` below. -->\n\n");
    s
}

/// Parsers block: grouped by Category (in [`CATEGORIES`] order),
/// columns `File | Summary`. Summary is verbatim from the header;
/// only newlines are collapsed to spaces so table cells stay on
/// a single row.
pub fn render_parsers_table(headers: &[SnippetHeader]) -> String {
    let mut out = generated_notice();
    out.push_str("| File | Summary |\n|---|---|\n");
    for category in CATEGORIES {
        let rows: Vec<&SnippetHeader> = headers
            .iter()
            .filter(|h| {
                h.kind == SnippetKind::Parser && h.get("Category").map(str::trim) == Some(*category)
            })
            .collect();
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!("| **{}** | |\n", category));
        for h in rows {
            out.push_str(&format!(
                "| `{}` | {} |\n",
                relative_display_path(&h.file),
                cell(summary_of(h))
            ));
        }
    }
    out
}

/// Composers block: flat, columns `File | Summary | Writes`.
/// The Writes column is the first whitespace-separated token of the
/// Writes value's first line — that is the composition slot the
/// composer produces, e.g. `workspace.lsis.ocsf`.
pub fn render_composers_table(headers: &[SnippetHeader]) -> String {
    let mut out = generated_notice();
    out.push_str("| File | Summary | Writes |\n|---|---|---|\n");
    for h in headers.iter().filter(|h| h.kind == SnippetKind::Composer) {
        out.push_str(&format!(
            "| `{}` | {} | `{}` |\n",
            relative_display_path(&h.file),
            cell(summary_of(h)),
            writes_first_token(h),
        ));
    }
    out
}

/// Filters block: flat, columns `File | Summary`.
pub fn render_filters_table(headers: &[SnippetHeader]) -> String {
    let mut out = generated_notice();
    out.push_str("| File | Summary |\n|---|---|\n");
    for h in headers.iter().filter(|h| h.kind == SnippetKind::Filter) {
        out.push_str(&format!(
            "| `{}` | {} |\n",
            relative_display_path(&h.file),
            cell(summary_of(h)),
        ));
    }
    out
}

/// Functions block: flat, columns `File | Signature | Used by`.
///
/// The Used-by column is derived by lexically scanning every snippet
/// file's body for calls to the function (see [`derive_used_by`]).
/// The result is a comma-separated list of caller stems, or `—` if
/// no callers are found — the Rule-of-Three adjudication surface.
pub fn render_functions_table(all_headers: &[SnippetHeader]) -> String {
    let mut out = generated_notice();
    out.push_str("| File | Signature | Used by |\n|---|---|---|\n");
    for h in all_headers.iter().filter(|h| h.kind == SnippetKind::Function) {
        let sig = h.get("Signature").unwrap_or("").trim();
        let name = parse_signature(sig).map(|(n, _)| n).unwrap_or_default();
        let callers = derive_used_by(&name, &h.file, all_headers);
        let callers_cell = if callers.is_empty() {
            "—".to_string()
        } else {
            callers
                .iter()
                .map(|p| format!("`{}`", file_stem(p).unwrap_or_default()))
                .collect::<Vec<_>>()
                .join(", ")
        };
        out.push_str(&format!(
            "| `{}` | `{}` | {} |\n",
            relative_display_path(&h.file),
            cell(sig.to_string()),
            callers_cell,
        ));
    }
    out
}

// ---------------------------------------------------------------------------
// Used-by derivation (lexical, scoped to shipped snippet bodies).
// ---------------------------------------------------------------------------

/// Scan every shipped snippet's BODY for calls to `func_name` and
/// return the caller files (excluding the defining file's own
/// declaration line). This is the Used-by inventory column — the
/// authoritative Rule-of-Three surface.
///
/// Scope discipline (see `limpid-snippet-header-schema-open-questions`
/// § sol guardrail (a)):
/// - only files under `packaging/snippets/**/*.limpid` — not README
///   examples, not test fixtures, not repo prose
/// - only file BODIES (past the first non-`//` line) — headers
///   don't count as call sites
/// - comment lines within the body (leading `//`) are stripped before
///   matching — a call written in a comment is not a call
/// - the defining file's own `def function <name>(` declaration line
///   is excluded — the declaration itself is not a caller
/// - the match is boundary-checked: `parse_kv(` matches `parse_kv(x)`
///   but NOT `parse_kv2(x)`
pub fn derive_used_by(
    func_name: &str,
    defining_file: &std::path::Path,
    all_headers: &[SnippetHeader],
) -> Vec<std::path::PathBuf> {
    if func_name.is_empty() {
        return Vec::new();
    }
    let mut callers = Vec::new();
    for h in all_headers {
        if file_calls(func_name, &h.content, h.file == defining_file) {
            callers.push(h.file.clone());
        }
    }
    callers.sort();
    callers
}

/// True if `content`'s body (past the header block) contains at
/// least one call to `func_name`, excluding comment lines and the
/// defining file's own `def function <name>(` declaration.
fn file_calls(func_name: &str, content: &str, is_defining_file: bool) -> bool {
    let decl_needle = format!("def function {func_name}(");
    let mut in_header = true;
    for line in content.lines() {
        if in_header {
            if line.starts_with("//") || line.trim().is_empty() {
                continue;
            }
            in_header = false;
        }
        let trimmed = line.trim_start();
        if trimmed.starts_with("//") {
            continue;
        }
        // Skip the declaration line in the defining file.
        if is_defining_file && trimmed.contains(&decl_needle) {
            continue;
        }
        if contains_call(line, func_name) {
            return true;
        }
    }
    false
}

/// Boundary-checked match: return true if `line` contains
/// `<func_name>(` where the char immediately before `<func_name>` is
/// not an identifier character (or the line starts with the match).
fn contains_call(line: &str, func_name: &str) -> bool {
    let needle = format!("{func_name}(");
    let mut start = 0;
    while let Some(pos) = line[start..].find(&needle) {
        let abs = start + pos;
        let prev_ok = abs == 0
            || {
                let before = &line[..abs];
                !before
                    .chars()
                    .next_back()
                    .map(|c| c.is_ascii_alphanumeric() || c == '_')
                    .unwrap_or(false)
            };
        if prev_ok {
            return true;
        }
        start = abs + needle.len();
    }
    false
}

// ---------------------------------------------------------------------------
// Small helpers.
// ---------------------------------------------------------------------------

/// The Summary value with newlines collapsed to single spaces so the
/// cell renders on a single row. Missing Summary → empty string
/// (lint has already reported it as an error before we get here).
fn summary_of(h: &SnippetHeader) -> String {
    h.get("Summary")
        .unwrap_or("")
        .replace('\n', " ")
        .trim()
        .to_string()
}

/// The first whitespace-separated token of the Writes value's first
/// line (e.g. `workspace.lsis.ocsf`). Empty when Writes is missing.
fn writes_first_token(h: &SnippetHeader) -> String {
    let writes = h.get("Writes").unwrap_or("");
    let first_line = writes.split('\n').next().unwrap_or("");
    first_line.split_whitespace().next().unwrap_or("").to_string()
}

/// Escape characters that would break markdown table cells. Pipe is
/// the classic offender; the rest of markdown syntax is fine in a
/// cell body.
fn cell(s: String) -> String {
    s.replace('|', "\\|")
}

/// `packaging/snippets/parsers/parse_foo.limpid` →
/// `parsers/parse_foo.limpid` (the trailing two components).
fn relative_display_path(file: &Path) -> String {
    file.components()
        .rev()
        .take(2)
        .collect::<Vec<_>>()
        .iter()
        .rev()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn file_stem(file: &Path) -> Option<String> {
    file.file_stem().map(|s| s.to_string_lossy().into_owned())
}

// ---------------------------------------------------------------------------
// BEGIN/END region substitution.
// ---------------------------------------------------------------------------

/// Replace the content between `<!-- BEGIN: <marker> -->` and
/// `<!-- END: <marker> -->` in `text` with `generated`. Both marker
/// tags are preserved verbatim; only the bytes between them are
/// substituted.
pub fn replace_marked_region(text: &str, marker: &str, generated: &str) -> Result<String, String> {
    let begin_tag = format!("<!-- BEGIN: {marker} -->");
    let end_tag = format!("<!-- END: {marker} -->");
    let begin_pos = text
        .find(&begin_tag)
        .ok_or_else(|| format!("BEGIN marker not found: {begin_tag}"))?;
    let after_begin = begin_pos + begin_tag.len();
    let end_pos = text[after_begin..]
        .find(&end_tag)
        .ok_or_else(|| format!("END marker not found after BEGIN: {end_tag}"))?
        + after_begin;

    let mut out = String::with_capacity(text.len() + generated.len());
    out.push_str(&text[..after_begin]);
    out.push('\n');
    out.push_str(generated);
    if !generated.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&text[end_pos..]);
    Ok(out)
}

// ---------------------------------------------------------------------------
// Tests.
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::header::parse_str;

    fn mk(kind: SnippetKind, path: &str, content: &str) -> SnippetHeader {
        parse_str(std::path::Path::new(path), kind, content).unwrap()
    }

    #[test]
    fn contains_call_boundary_check() {
        assert!(contains_call("workspace.x = parse_kv(y)", "parse_kv"));
        assert!(!contains_call("workspace.x = parse_kv2(y)", "parse_kv"));
        assert!(!contains_call("workspace.x = my_parse_kv(y)", "parse_kv"));
        assert!(contains_call("parse_kv(y)", "parse_kv"));
    }

    #[test]
    fn used_by_excludes_header_and_comments() {
        // Defining file: proto_num function.
        let def_file = "/repo/packaging/snippets/functions/proto_num.limpid";
        let def_content = "\
// Summary:     IANA proto
// Signature:   proto_num(name) → Int | null
// Test corpus: unit (registry)

def function proto_num(name) {
    switch lower(name) {
        \"tcp\" { 6 }
        default { null }
    }
}
";
        let def_header = mk(SnippetKind::Function, def_file, def_content);

        // Caller in the header — must NOT count (headers don't call).
        let caller_header_only = mk(
            SnippetKind::Parser,
            "/repo/packaging/snippets/parsers/parse_x.limpid",
            "\
// Summary:     Look, proto_num(6) in the header
// Reads:       ingress (raw wire) — X
// Writes:      workspace.lsis.* — 4001
// Category:    Network firewall / IPS
// Test corpus: real (x)

def process x {}
",
        );

        // Caller in the body — must count.
        let caller_body = mk(
            SnippetKind::Parser,
            "/repo/packaging/snippets/parsers/parse_y.limpid",
            "\
// Summary:     Y
// Reads:       ingress (raw wire) — Y
// Writes:      workspace.lsis.* — 4001
// Category:    Network firewall / IPS
// Test corpus: real (y)

def process y {
    workspace.lsis.proto = proto_num(workspace.raw.proto)
}
",
        );

        // Comment-only body reference — must NOT count.
        let caller_comment = mk(
            SnippetKind::Parser,
            "/repo/packaging/snippets/parsers/parse_z.limpid",
            "\
// Summary:     Z
// Reads:       ingress (raw wire) — Z
// Writes:      workspace.lsis.* — 4001
// Category:    Network firewall / IPS
// Test corpus: real (z)

def process z {
    // proto_num(x) would work here but we compute inline instead
    workspace.lsis.proto = 6
}
",
        );

        let all = vec![def_header.clone(), caller_header_only, caller_body.clone(), caller_comment];
        let callers = derive_used_by("proto_num", &def_header.file, &all);
        assert_eq!(callers, vec![caller_body.file.clone()]);
    }

    #[test]
    fn used_by_excludes_defining_file_declaration_line_but_would_count_body_use() {
        // If the function references itself elsewhere in its own file
        // (banned by the analyzer but possible to text-match), only
        // the declaration line is skipped — other lines still count.
        // Analyzer bans recursion, so in practice this stays 0, but
        // the guardrail should be surgical.
        let def_content = "\
// Summary:     Self-caller
// Signature:   selfy(x) → Int
// Test corpus: unit (docs)

def function selfy(x) {
    selfy(x - 1)
}
";
        let def_file = "/repo/packaging/snippets/functions/selfy.limpid";
        let def = mk(SnippetKind::Function, def_file, def_content);
        // The declaration line `def function selfy(` is skipped; the
        // recursion in the body still counts. So Used-by lists the
        // defining file itself.
        let callers = derive_used_by("selfy", &def.file, &[def.clone()]);
        assert_eq!(callers, vec![def.file.clone()]);
    }

    #[test]
    fn parsers_table_grouped_by_category() {
        let a = mk(
            SnippetKind::Parser,
            "/r/packaging/snippets/parsers/parse_a.limpid",
            "\
// Summary:     A summary
// Reads:       ingress (raw wire) — A
// Writes:      workspace.lsis.* — 4001
// Category:    Transport
// Test corpus: real (a)
",
        );
        let b = mk(
            SnippetKind::Parser,
            "/r/packaging/snippets/parsers/parse_b.limpid",
            "\
// Summary:     B summary
// Reads:       ingress (raw wire) — B
// Writes:      workspace.lsis.* — 4001
// Category:    Network firewall / IPS
// Test corpus: real (b)
",
        );
        let out = render_parsers_table(&[a, b]);
        // Transport appears before Network firewall in CATEGORIES.
        let t = out.find("**Transport**").unwrap();
        let n = out.find("**Network firewall / IPS**").unwrap();
        assert!(t < n);
        assert!(out.contains("parse_a.limpid"));
        assert!(out.contains("parse_b.limpid"));
    }

    #[test]
    fn composers_table_prints_writes_first_token() {
        let c = mk(
            SnippetKind::Composer,
            "/r/packaging/snippets/composers/compose_ocsf.limpid",
            "\
// Summary:     Renders LSIS to OCSF 1.3.0
// Reads:       workspace.lsis.* (LSIS)
//                .class_uid (required, Int) — dispatch discriminator
// Writes:      workspace.lsis.ocsf — OCSF 1.3.0 JSON string
// Test corpus: real (r)
",
        );
        let out = render_composers_table(&[c]);
        assert!(out.contains("`workspace.lsis.ocsf`"));
        assert!(out.contains("Renders LSIS to OCSF 1.3.0"));
    }

    #[test]
    fn replace_marked_region_basic() {
        let input = "prefix\n<!-- BEGIN: foo -->\nold\n<!-- END: foo -->\nsuffix\n";
        let out = replace_marked_region(input, "foo", "new content").unwrap();
        assert!(out.contains("<!-- BEGIN: foo -->\nnew content\n<!-- END: foo -->"));
        assert!(out.contains("prefix"));
        assert!(out.contains("suffix"));
    }

    #[test]
    fn replace_marked_region_missing_begin_errors() {
        assert!(replace_marked_region("no markers", "foo", "x").is_err());
    }
}
