//! Inventory markdown emission and BEGIN/END region replacement.
//!
//! Renders the parser inventory table from per-file
//! [`ParserHeader`]s and substitutes it into a markdown file
//! between matched `<!-- BEGIN: inventory:parsers -->` and
//! `<!-- END: inventory:parsers -->` markers.
//!
//! Only the parsers inventory is regenerated by this tool today.
//! The `inventory:composers` / `:filters` / `:functions` blocks
//! in the README stay hand-maintained — those collections are
//! small enough that hand-sync drift is low cost.

use std::path::Path;

use crate::header::ParserHeader;

/// Soft categorization for the inventory table. New parsers
/// without a category entry land in [`UNCATEGORISED_CATEGORY`] at
/// the end of the table — the developer adding the parser should
/// extend the mapping below in the same commit.
const CATEGORIES: &[(&str, &[&str])] = &[
    ("Transport", &["parse_syslog", "parse_journald"]),
    (
        "Security devices / cloud audit",
        &[
            "parse_fortigate_cef",
            "parse_fortigate_syslog",
            "parse_paloalto_cef",
            "parse_paloalto_syslog",
            "parse_asa",
            "parse_cloudtrail",
            "parse_juniper_srx_sd_syslog",
            "parse_juniper_srx_syslog",
            "parse_nsp",
            "parse_checkpoint_leef",
            "parse_checkpoint_syslog",
        ],
    ),
    (
        "OSS NDR",
        &[
            "parse_suricata",
            "parse_zeek_default",
            "parse_zeek_soc",
            "parse_zeek_full",
        ],
    ),
    (
        "Server / host vocabulary",
        &[
            "parse_openssh",
            "parse_sudo",
            "parse_combined_log",
            "parse_postfix",
            "parse_winevent_json",
            "parse_sysmon",
            "parse_bind",
            "parse_auditd",
        ],
    ),
    ("Vendor-neutral", &["parse_ocsf"]),
];

const UNCATEGORISED_CATEGORY: &str = "Uncategorised";

const PARSERS_MARKER: &str = "inventory:parsers";

/// Render the parsers inventory as a markdown table body
/// (without the surrounding BEGIN/END markers).
///
/// Returns the rendered table and a list of warnings — currently
/// only "category map references a parser file that doesn't
/// exist", which is the most-likely sign of stale `CATEGORIES`
/// after a parser file is renamed or removed.
pub fn render_parsers_table(headers: &[ParserHeader]) -> (String, Vec<String>) {
    let mut out = String::new();
    let mut warnings = Vec::new();

    out.push_str("<!-- Generated by `cargo xtask gen-snippet-inventory`. Do not\n");
    out.push_str("     edit by hand — edit the parser headers and re-run the\n");
    out.push_str("     generator. See `Authoring conventions` below. -->\n\n");
    out.push_str("| File | Source |\n");
    out.push_str("|---|---|\n");

    // First pass: gather all Source strings keyed by parser stem
    // so that within-category duplicates can be disambiguated.
    let sources: std::collections::HashMap<String, String> = headers
        .iter()
        .filter_map(|h| {
            file_stem(&h.file).map(|stem| (stem, derive_source(h)))
        })
        .collect();

    let mut emitted = std::collections::HashSet::new();
    for (category, parsers) in CATEGORIES {
        let mut rows: Vec<&ParserHeader> = Vec::new();
        for p in *parsers {
            match headers
                .iter()
                .find(|h| file_stem(&h.file).as_deref() == Some(*p))
            {
                Some(h) => rows.push(h),
                None => warnings.push(format!(
                    "CATEGORIES references `{p}` but no matching parser \
                     file was found under packaging/snippets/parsers/. \
                     Drop the entry from `crates/xtask/src/inventory.rs::CATEGORIES`."
                )),
            }
        }
        if rows.is_empty() {
            continue;
        }
        out.push_str(&format!("| **{}** | |\n", category));
        emit_category_rows(&mut out, &rows, &sources);
        for h in rows {
            if let Some(stem) = file_stem(&h.file) {
                emitted.insert(stem);
            }
        }
    }

    // Anything in `headers` that wasn't matched by the category
    // map goes here. New parsers land here until the CATEGORIES
    // table is updated.
    let leftovers: Vec<&ParserHeader> = headers
        .iter()
        .filter(|h| {
            file_stem(&h.file)
                .map(|s| !emitted.contains(&s))
                .unwrap_or(false)
        })
        .collect();
    if !leftovers.is_empty() {
        out.push_str(&format!("| **{}** | |\n", UNCATEGORISED_CATEGORY));
        warnings.push(format!(
            "{} parser(s) not in `crates/xtask/src/inventory.rs::CATEGORIES`; \
             they appear under `{}` until the map is extended.",
            leftovers.len(),
            UNCATEGORISED_CATEGORY
        ));
        emit_category_rows(&mut out, &leftovers, &sources);
    }

    (out, warnings)
}

/// Emit table rows for parsers in a single category, disambiguating
/// the Source column when two rows in this category would render
/// identically. Disambiguation appends a tail of the form
/// `(scope: <stem-tail>)` derived from the file stem so an
/// otherwise-identical Source is distinguishable to a reader.
fn emit_category_rows(
    out: &mut String,
    rows: &[&ParserHeader],
    sources: &std::collections::HashMap<String, String>,
) {
    // Count how many rows in this category produce each Source
    // value, so we know which need disambiguation.
    let mut source_counts: std::collections::HashMap<&str, usize> =
        std::collections::HashMap::new();
    for h in rows {
        if let Some(stem) = file_stem(&h.file)
            && let Some(src) = sources.get(&stem)
        {
            *source_counts.entry(src.as_str()).or_insert(0) += 1;
        }
    }

    for h in rows {
        let path = relative_display_path(&h.file);
        let stem = file_stem(&h.file).unwrap_or_default();
        let source = sources
            .get(&stem)
            .cloned()
            .unwrap_or_default();

        // Disambiguate same-Source rows by appending the
        // distinctive tail of the file stem. `parse_zeek_soc` ⇒
        // `soc`, `parse_zeek_full` ⇒ `full`, `parse_juniper_srx_sd_syslog`
        // ⇒ `sd_syslog`, etc.
        let final_source = if source_counts.get(source.as_str()).copied().unwrap_or(0) > 1 {
            let suffix = stem_disambiguator(&stem);
            if suffix.is_empty() {
                source
            } else {
                format!("{source} (scope: {suffix})")
            }
        } else {
            source
        };

        out.push_str(&format!("| `{}` | {} |\n", path, final_source));
    }
}

/// Strip `**bold**` markdown emphasis from a string. Markdown
/// emphasis renders inside table cells but reads as visual noise
/// when the cell's purpose is identification, not styling.
fn strip_bold_markup(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch == '*' && chars.peek() == Some(&'*') {
            chars.next(); // drop the second '*'
            continue;
        }
        out.push(ch);
    }
    out
}

/// Distinctive tail of a parser file stem, used to disambiguate
/// same-Source rows. Strips the common `parse_` prefix and any
/// vendor token prefix that appears on multiple files.
///
/// Best-effort heuristic, since the function has no knowledge of
/// what's distinctive — it just returns the underscore-segments
/// after the first segment. For `parse_zeek_full` that's `full`;
/// for `parse_juniper_srx_sd_syslog` it's `srx_sd_syslog` — still
/// noisy but informative enough to discriminate.
fn stem_disambiguator(stem: &str) -> String {
    let after_prefix = stem.strip_prefix("parse_").unwrap_or(stem);
    after_prefix
        .split_once('_')
        .map(|x| x.1)
        .unwrap_or("")
        .to_string()
}

/// `packaging/snippets/parsers/parse_foo.limpid` →
/// `parsers/parse_foo.limpid` (the trailing two components).
fn relative_display_path(file: &Path) -> String {
    file.components()
        .rev()
        .take(2)
        .collect::<Vec<_>>()
        .iter()
        .rev()
        .map(|c| c.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn file_stem(file: &Path) -> Option<String> {
    file.file_stem().map(|s| s.to_string_lossy().into_owned())
}

/// Derive the "Source" column from the parser header. The aim is
/// a 1-line summary; we prefer the `Vendor:` first clause as the
/// primary signal, joined with a short Wire-derived qualifier
/// when the resulting line stays under the soft length budget.
///
/// "First clause" means: the value up to (but not including) the
/// earliest of `.`, `;`, ` — `, or end-of-line.
fn derive_source(h: &ParserHeader) -> String {
    let vendor = h.get("Vendor").map(first_clause).unwrap_or_default();
    let wire = h.get("Wire").map(first_clause).unwrap_or_default();

    let joined = if vendor.is_empty() {
        wire
    } else if wire.is_empty() || wire == vendor {
        vendor
    } else {
        // If the vendor line already mentions the wire shape,
        // don't duplicate.
        let v_lower = vendor.to_lowercase();
        let w_lower = wire.to_lowercase();
        let wire_first_word = w_lower.split_whitespace().next().unwrap_or("");
        if !wire_first_word.is_empty() && v_lower.contains(wire_first_word) {
            vendor
        } else {
            let candidate = format!("{} — {}", vendor, wire);
            if candidate.chars().count() > 140 {
                vendor
            } else {
                candidate
            }
        }
    };
    // Strip markdown emphasis from the final cell value so the
    // table reads cleanly and duplicate detection (in the caller)
    // works on the same canonical form that's emitted.
    strip_bold_markup(&joined)
}

/// First clause of a free-text value: up to but not including the
/// earliest of `.` / `;` followed by space/EOL, or ` — `
/// (space-em-dash-space). Parenthetical and bracketed regions are
/// treated as opaque — boundary characters inside `(...)` /
/// `[...]` / `{...}` are not clause breaks, so multi-clause
/// content inside parens is preserved as one unit and balanced
/// brackets are not orphaned.
///
/// Backtick-delimited code spans are likewise opaque: a `;` or `.`
/// inside `` `...` `` does not trigger a clause break, so a
/// literal `` `; ` `` (e.g. an inline code sample of a key/value
/// separator) does not orphan its backticks or truncate the
/// clause mid-span.
fn first_clause(value: &str) -> String {
    // Operate on a flattened (single-line) version because the
    // value may have continuation-induced newlines that we want to
    // treat as whitespace for the purposes of clause extraction.
    let flat = value.replace('\n', " ");
    let flat = flat.trim();

    let bytes = flat.as_bytes();
    let mut end = flat.len();
    let mut depth: i32 = 0;
    let mut in_code = false;
    let mut i = 0;
    while i < bytes.len() {
        let ch = flat[i..].chars().next().unwrap();
        let ch_len = ch.len_utf8();

        if ch == '`' {
            in_code = !in_code;
            i += ch_len;
            continue;
        }

        if !in_code {
            match ch {
                '(' | '[' | '{' => depth += 1,
                ')' | ']' | '}' => depth = (depth - 1).max(0),
                _ => {}
            }
        }

        if depth == 0 && !in_code {
            if (ch == '.' || ch == ';')
                && flat[i + ch_len..]
                    .chars()
                    .next()
                    .map(char::is_whitespace)
                    .unwrap_or(true)
            {
                end = i;
                break;
            }
            if flat[i..].starts_with(" — ") {
                end = i;
                break;
            }
        }

        i += ch_len;
    }

    flat[..end].trim().to_string()
}

/// Replace the content between `<!-- BEGIN: <marker> -->` and
/// `<!-- END: <marker> -->` in `text` with `generated`.
/// Both marker tags are preserved verbatim; only the bytes
/// between them are substituted.
pub fn replace_marked_region(text: &str, marker: &str, generated: &str) -> Result<String, String> {
    let begin_tag = format!("<!-- BEGIN: {marker} -->");
    let end_tag = format!("<!-- END: {marker} -->");
    let begin_pos = text
        .find(&begin_tag)
        .ok_or_else(|| format!("BEGIN marker not found: {begin_tag}"))?;
    let after_begin = begin_pos + begin_tag.len();
    let end_pos = text[after_begin..]
        .find(&end_tag)
        .ok_or_else(|| format!("END marker not found after BEGIN: {end_tag}"))?
        + after_begin;

    let mut out = String::with_capacity(text.len() + generated.len());
    out.push_str(&text[..after_begin]);
    out.push('\n');
    out.push_str(generated);
    if !generated.ends_with('\n') {
        out.push('\n');
    }
    out.push_str(&text[end_pos..]);
    Ok(out)
}

/// Marker name used for the parsers inventory block.
pub fn parsers_marker() -> &'static str {
    PARSERS_MARKER
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn first_clause_stops_at_period_space() {
        assert_eq!(first_clause("foo bar. baz qux"), "foo bar");
    }

    #[test]
    fn first_clause_stops_at_semicolon() {
        assert_eq!(first_clause("foo bar; baz qux"), "foo bar");
    }

    #[test]
    fn first_clause_stops_at_em_dash() {
        assert_eq!(first_clause("foo bar — baz qux"), "foo bar");
    }

    #[test]
    fn first_clause_keeps_decimals() {
        // A `.` not followed by whitespace (e.g. `1.3.0`) is NOT
        // a clause boundary.
        assert_eq!(first_clause("FortiOS 6.x / 7.x with cef"), "FortiOS 6.x / 7.x with cef");
    }

    #[test]
    fn first_clause_handles_multiline() {
        assert_eq!(
            first_clause("FortiGate (FortiOS 6.x)\nfrom Fortinet"),
            "FortiGate (FortiOS 6.x) from Fortinet"
        );
    }

    #[test]
    fn first_clause_respects_paren_depth() {
        // The `;` and `—` inside `(...)` must NOT trigger a clause
        // break — otherwise the closing paren is orphaned.
        assert_eq!(
            first_clause("FortiGate (FortiOS 6.x / 7.x with `set format cef`; from Fortinet)"),
            "FortiGate (FortiOS 6.x / 7.x with `set format cef`; from Fortinet)"
        );
        assert_eq!(
            first_clause("Vendor (a — b) suffix"),
            "Vendor (a — b) suffix"
        );
        // Outside parens, the break still applies.
        assert_eq!(
            first_clause("Vendor (a; b); after"),
            "Vendor (a; b)"
        );
    }

    #[test]
    fn replace_marked_region_basic() {
        let input = "\
prefix
<!-- BEGIN: foo -->
old content
<!-- END: foo -->
suffix
";
        let out = replace_marked_region(input, "foo", "new content").unwrap();
        assert!(out.contains("<!-- BEGIN: foo -->\nnew content\n<!-- END: foo -->"));
        assert!(out.contains("prefix"));
        assert!(out.contains("suffix"));
    }

    #[test]
    fn replace_marked_region_errors_on_missing_marker() {
        let input = "no markers here";
        let err = replace_marked_region(input, "foo", "x").unwrap_err();
        assert!(err.contains("BEGIN marker not found"));
    }
}
